version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
      POSTGRES_DB: crypto_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - crypto-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crypto_user -d crypto_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crypto-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # ClickHouse for analytics
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: crypto_analytics
      CLICKHOUSE_USER: crypto_user
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    networks:
      - crypto-network



  # Main crypto data pipeline
  crypto-data-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=crypto_data
      - POSTGRES_USER=crypto_user
      - POSTGRES_PASSWORD=crypto_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - crypto-network

volumes:
  postgres_data:
  clickhouse_data:
  redis_data:

networks:
  crypto-network:
    driver: bridge