[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = false
runOnSave = true
enableCORS = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
